version: "3"

services:
  api:
    container_name: regret_api
    hostname: regret_api
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    ports:
      - ${APP_EXPOSE_PORT}:${APP_PORT}
    restart: always
    depends_on:
      - db

networks:
  default:
    name: regret_network
