.PHONY: key

up:
	-docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d --build

down:
	-docker-compose down

migrate/up:
	docker-compose exec db ./migrate up

key:
	./app_key_generator
