.PHONY: key

up:
	-docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d --build

down:
	-docker compose down

migrate/up:
	docker exec -it regret_api ./migrate up

key:
	go run app_key_generator.go
