version: "3"

services:
  cpanel:
    container_name: regret_cpanel
    hostname: regret_cpanel
    build: .
    ports:
      - ${APP_EXPOSE_PORT}:3000
    restart: always

networks:
  default:
    name: regret_network
